Rel 647921 add changes from spark operator
relativityone/spark-on-k8s-operator pull request #12
Opened 2022-04-01 17:32 UTC by matthewthekramer

Update go to 1.18
Update charts
add secrets to main workflow

2022-04-01 20:25 UTC, meggers requested changes

2022-04-01 20:25 UTC, meggers commented on charts/spark-operator-chart/templates/webhook-cleanup-job.yaml
> +        nodeSelector was added by Relativity, we should push this upstream
Remove this comment

2022-04-01 20:25 UTC, meggers commented on charts/spark-operator-chart/templates/webhook-init-job.yaml
> +         nodeSelector was added by Relativity, we should push this upstream
Remove this comment

2022-04-12 13:31 UTC, meggers requested changes

2022-04-12 18:20 UTC, matthewthekramer commented on .github/workflows/pull_upstream.yml
> +name: 'Upstream Sync'
Not sure why this is showing on diff... this file is already on base branch

2022-04-12 20:27 UTC, HawaiianSpork approved these changes

2022-04-14 13:10 UTC, meggers approved these changes

2022-04-14 13:40 UTC, merged